#Server
server.port=8080
spring.application.name=ai-chatbot-backend

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
app.session.ttl-minutes=30

#LLM API
app.openai.api-key=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
app.openai.base-url=https://api.openai.com/v1
app.openai.model=gpt-4.1-mini
app.openai.max-tokens=1024
app.openai.system-prompt=You are a helpful, context-aware assistant. Use the conversation history to provide relevant, coherent responses.

#Context Window Management
app.chat.max-context-messages=20

#Actuator(Health check PostgreSQL and Redis)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
